package.json
The latest version adds a lot of performance improvements
=> Update redux-devtools to version 2.1.5

app/store/configureStore.js, conf/webpack.production.js
Some webpack and redux store configs were not working
on production settings.
Refs #30.
=> Fix production build configuration

app/actions/purposeActions.js, app/actions/resourceActions.js, app/actions/unitActions.js, app/middleware/Schemas.js, app/reducers/__tests__/searchReducer.spec.js, app/reducers/searchReducer.js
=> Migrate to the new paginated API schema

app/components/purpose/PurposeCategory.js
=> Collapse home page purpose categories on default

app/assets/styles/layout.less, app/containers/App.js, app/index.js, conf/template.html
Use flexbox to support sticky footer without fixing the
footer height.
Closes #70.
=> Make footer work even when height is not fixed

app/utils/DataUtils.js, app/utils/__tests__/DataUtils.spec.js
=> Round available hours upwards to nearest 0.5

app/actions/purposeActions.js, app/actions/resourceActions.js, app/actions/unitActions.js, app/utils/APIUtils.js, app/utils/__tests__/APIUtils.spec.js, package.json
=> Update redux-api-middleware to latest version

app/components/common/ImagePanel.js, app/components/common/__tests__/ImagePanel.spec.js
=> Make resource page images collapsed on default

app/assets/styles/about-page.less, app/assets/styles/app.less, app/components/layout/Navbar.js, app/containers/AboutPage.js, app/routes.js
=> Add about Respa -page

app/utils/DataUtils.js, app/utils/__tests__/DataUtils.spec.js
=> Fix available time with long ongoing reservations

app/actions/reservationActions.js
=> Use JWT token when fetching user reservations

app/containers/AboutPage.js
=> Add real content to about page

app/components/search/SearchFilters.js, app/constants/AppConstants.js, app/selectors/__tests__/searchFiltersSelector.spec.js
=> Add people capacity filter to search page

app/components/layout/Navbar.js, app/components/layout/__tests__/Navbar.spec.js, app/containers/App.js, app/containers/__tests__/App.spec.js, app/selectors/containers/__tests__/appSelector.spec.js, app/selectors/containers/appSelector.js
=> Use better isLoggedIn check on navbar

app/containers/ReservationForm.js, app/containers/SearchControls.js, package.json
=> Fix calendar not showing on IE11 issue

app/components/layout/Footer.js
=> Remove "Pilotissa mukana" section from footer

app/selectors/__tests__/sortedReservationsSelector.spec.js, app/selectors/sortedReservationsSelector.js
=> Switch order of user reservations

app/components/layout/Navbar.js, app/components/layout/__tests__/Navbar.spec.js, app/fixtures/User.js
=> Use user first name and last name in navbar

app/reducers/notificationsReducer.js
=> Use translated error messages from API

app/components/purpose/PurposeCategory.js, app/components/purpose/__tests__/PurposeCategory.spec.js, app/constants/AppConstants.js, app/containers/PurposeCategoryList.js, app/containers/__tests__/PurposeCategoryList.spec.js, app/fixtures/Purpose.js, app/selectors/__tests__/groupedPurposesSelector.spec.js, app/selectors/__tests__/purposeCategoriesSelector.spec.js, app/selectors/containers/purposeCategoryListSelector.js, app/selectors/groupedPurposesSelector.js, app/selectors/purposeCategoriesSelector.js, app/utils/DataUtils.js, app/utils/__tests__/DataUtils.spec.js
=> Use new translated purpose category headers

app/constants/AppConstants.js
=> Switch API requests to use https

app/components/reservation/TimeSlot.js
=> Show reservation user information for admins

app/components/layout/Navbar.js
=> Show user email in navbar if names are undefined

app/store/configureStore.js, server/main.js
=> Use Browser history instead of Hash history

app/containers/ReservationsList.js, app/containers/__tests__/ReservationsList.spec.js
=> Use isOwn query param on my reservations lits

app/components/reservation/ConfirmReservationModal.js, app/containers/ReservationForm.js, app/containers/__tests__/ReservationForm.spec.js
Make sure reservation comments are not overwritten if
regular user edits reservation.
=> Fix issues with reservation comments

app/assets/styles/tables.less, app/assets/styles/time-slots.less, app/components/reservation/TimeSlot.js, app/utils/TimeUtils.js, app/utils/__tests__/TimeUtils.spec.js
Makes reservations more distinct from one another and
displays reservation info and controls only once per reservation.
Closes #185.
=> Improve admin reservation functionality styles

app/components/layout/Navbar.js, server/main.js
=> Clear cookie session on logout

app/components/reservation/ReservationInfo.js
=> Show login text only if resource is reservable

app/index.js
=> Fix logout link on IE

app/containers/AboutPage.js
=> Add register details link

server/Html.js
=> Add Piwik analytics code

app/components/resource/ResourceDetails.js, app/components/resource/__tests__/ResourceDetails.spec.js, package.json
=> Add autolinking to resource description texts

app/components/common/DateHeader.js, app/components/common/ImagePanel.js, app/components/layout/Footer.js, app/components/layout/Navbar.js, app/components/purpose/PurposeCategory.js, app/components/purpose/PurposeCategoryItem.js, app/components/reservation/ConfirmReservationModal.js, app/components/reservation/ReservationControls.js, app/components/reservation/ReservationFormControls.js, app/components/reservation/ReservationInfo.js, app/components/reservation/TimeSlot.js, app/components/reservation/TimeSlots.js, app/components/search/SearchFilters.js, app/components/search/SearchResult.js, app/components/search/SearchResults.js, app/components/search/TypeaheadList.js, app/containers/App.js, app/containers/NotFoundPage.js, app/containers/ReservationDeleteModal.js, app/containers/ReservationPage.js, app/containers/ResourcePage.js, app/containers/SearchControls.js
Keeps the webpack bundle size smaller when only the
components that are used are imported from React Bootstrap.
Refs #237.
=> Import individual react bootsrap components

server/config.js, server/main.js
=> Makes pod start work in every folder

server/config.js, server/configurePassport.js
Move passport login callback url to server configs.
Refs #192.
=> Add login callback url to server configs

server/config.js
=> Make server port configurable with env variables

config/webpack.development.js, config/webpack.production.js
=> Make api url configurable with env variables

app/components/reservation/ReservationCalendarControls.js, app/components/reservation/TimeSlotControls.js, app/components/reservation/__tests__/ReservationCalendarControls.spec.js, app/components/reservation/__tests__/TimeSlotControls.spec.js, app/containers/ReservationCancelModal.js, app/containers/ReservationDeleteModal.js, app/containers/ReservationForm.js, app/containers/__tests__/ReservationCancelModal.spec.js, app/containers/__tests__/ReservationDeleteModal.spec.js, app/containers/__tests__/ReservationForm.spec.js
=> Improve cancel buttons wording

app/containers/ReservationForm.js
=> Improve reservation form styles

app/components/reservation/ConfirmReservationModal.js
=> Update preliminary reservation form intro text

app/containers/ReservationCancelModal.js, app/containers/__tests__/ReservationCancelModal.spec.js
=> Use responsibleContactInfo in cancel modal

app/components/reservation/TimeSlot.js, app/components/reservation/TimeSlots.js, app/components/reservation/__tests__/TimeSlot.spec.js, app/components/reservation/__tests__/TimeSlots.spec.js, app/containers/ReservationCalendar.js, app/containers/__tests__/ReservationCalendar.spec.js
Allow preliminary reservations only if user has proper permissions.
Closes #310.
=> Fix user preliminary reservation rights

server/config.js, server/configurePassport.js
=> Use relative loginCallbackUrl, add proxy option

app/components/customization/AboutPageContent.js
Removes paragraph that is no longer relevant.
Closes #340.
=> Update about page texts

app/containers/ReservationInfoModal.js, app/containers/__tests__/ReservationInfoModal.spec.js
=> Remove edit button from reservation info modal

app/containers/ReservationInfoModal.js, app/containers/__tests__/ReservationInfoModal.spec.js
=> Don't allow commenting cancelled reservations

app/components/reservation/ConfirmReservationModal.js
=> Make confirm reservation modal backdrop static

app/fixtures/Resource.js, app/reducers/__tests__/adminResourcesPageReducer.spec.js, app/reducers/adminResourcesPageReducer.js
=> Filter out non public resources from adminResourcesPageReducer

app/screens/shared/resource-list/ResourceIcons.js, app/screens/shared/resource-list/ResourceIcons.spec.js, app/screens/shared/resource-list/ResourceListItem.js, app/screens/shared/resource-list/resource-list.less
=> Move icons to ResourceIcons and add price (refs #415)

app/components/resource/ResourcesTableItem.js, app/components/resource/__tests__/ResourcesTableItem.spec.js
=> Show "Closed" if resource is not yet opened

app/selectors/containers/__tests__/adminResourcesPageSelector.spec.js, app/selectors/containers/adminResourcesPageSelector.js
=> Order resources by name in adminResourcesPageSelector

app/screens/resource/resource-info/ImageCarousel.js, app/screens/resource/resource-info/ImageCarousel.spec.js
=> Add arrow controls to ImageCarousel

app/selectors/__tests__/sortedReservationsSelector.spec.js, app/selectors/sortedReservationsSelector.js
=> Fix "confirmed" filter in admin reservations

app/screens/shared/resource-icons/ResourceIcons.js, app/screens/shared/resource-icons/ResourceIcons.spec.js
=> Show "MAKSUTON" if there is no reservation cost

app/screens/resource/resource-info/ImageCarousel.js
=> Make sure small images look good in carousel

app/containers/ReservationSuccessModal.js
=> Remove contact info from ReservationSuccessModal

app/screens/search/results/ResultsCount.js, app/screens/search/results/ResultsCount.spec.js, app/screens/search/results/SearchResults.js, app/screens/search/results/SearchResults.spec.js
=> Add ResultsCount component to searchResults (refs #367)

app/pages/resource/reservation-confirmation/ConfirmReservationModal.js, app/pages/resource/reservation-confirmation/ConfirmReservationModal.spec.js
=> Don't show reservation terms for admins

app/constants/AppConstants.js, app/pages/search/controls/SearchControlsContainer.js, app/pages/search/controls/SearchControlsContainer.spec.js
=> Use localized date format in DateField

app/routes.js
Adds redirect from old reservation page to the new resource page.
Closes #470.
=> Add redirect from old reservation page

app/pages/search/controls/AdvancedSearch.js
=> Fix problem with clearing purpose in search

app/pages/resource/reservation-calendar/ReservationCalendarControls.js, app/pages/resource/reservation-calendar/time-slots/TimeSlot.js, app/pages/resource/reservation-info/ReservationInfo.js, app/pages/resource/reservation-info/ReservationInfo.spec.js, app/shared/modals/reservation-cancel/ReservationCancelModalContainer.js, app/shared/modals/reservation-cancel/ReservationCancelModalContainer.spec.js
Adds language support for reservationInfo and
responsibleContactInfo fields.
Closes #484.
=> Add language support for resource fields

README.md, package.json
This PR:
- Updates repo names and urls.
- Updates usage instruction on README.
=> Move repo to helsinki

app/shared/availability-view/availability-view.less
Closes #497.
Needs #496 to be merged first.
=> Fix Firefox style issue

app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.js, app/shared/availability-view/availability-view.less
Adds access code and comments to availability view reservation popovers.
Closes #504.
=> Add necessary info to reservation popover

app/shared/availability-view/AvailabilityView.js, app/shared/availability-view/AvailabilityView.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroups.js, app/shared/availability-view/TimelineGroups/TimelineGroups.spec.js
First part of #499. To test this in the browser you can for example use react-dev-tools to check AvailabilityView's state or provide `onSelect={(selection) => console.log(selection)}` to AvailabilityView.
=> Make reservations (part 1)

app/shared/reservation-access-code/ReservationAccessCode.js
=> Fix multiple colons issue on my reservations page

app/constants/AppConstants.js, app/pages/resource/reservation-confirmation/ConfirmReservationModal.js, app/pages/resource/reservation-confirmation/ConfirmReservationModal.spec.js, app/pages/resource/reservation-confirmation/ReservationForm.spec.js
=> Prefill event subject field on edit

app/shared/availability-view/AvailabilityView.js, app/shared/availability-view/AvailabilityView.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js, app/shared/availability-view/TimelineGroups/TimelineGroup/utils.js, app/shared/availability-view/TimelineGroups/TimelineGroup/utils.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroups.js, app/shared/availability-view/TimelineGroups/TimelineGroups.spec.js, app/shared/availability-view/availability-view.less, app/shared/availability-view/index.js
=> Highlighting

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/shared/availability-view/AvailabilityView.js, app/shared/availability-view/AvailabilityView.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js
=> AvailabilityView time selection popover

app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/utils.js, app/shared/availability-view/TimelineGroups/TimelineGroup/utils.spec.js, app/shared/availability-view/availability-view.less
=> Prevent invalid selections

app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimelineContainer.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/utils.js, app/shared/availability-view/TimelineGroups/TimelineGroup/utils.spec.js, app/shared/availability-view/availability-view.less
Closes #518.
Prevent making reservations outside the available hours and in the past.
=> Add available hours to own premises

app/shared/availability-view/AvailabilityView.js, app/shared/availability-view/AvailabilityView.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/AvailabilityTimeline.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js, app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js, app/shared/availability-view/TimelineGroups/TimelineGroups.js
=> Cancel AvailabilityView selection

app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js, app/shared/availability-view/availability-view.less
Closes #525. Merge #524 first.
=> Cancel selection from popover

app/shared/availability-view/AvailabilityView.js, app/shared/availability-view/Sidebar/GroupInfo/GroupInfo.js, app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.js, app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.spec.js, app/shared/availability-view/Sidebar/Sidebar.js, app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js, app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.spec.js, app/shared/availability-view/availability-view.less
=> Highlight selected time and resource

app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js, app/shared/availability-view/TimelineGroups/TimelineGroups.js, app/shared/availability-view/TimelineGroups/TimelineGroups.spec.js, app/shared/availability-view/availability-view.less, package.json
=> Make AvailabilityView time bar sticky

app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.js, app/shared/availability-view/TimelineGroups/TimelineGroup/TimelineGroup.spec.js, app/shared/availability-view/availability-view.less
=> Show line for current time

app/shared/availability-view/TimelineGroups/TimelineGroup/utils.js, app/shared/availability-view/TimelineGroups/TimelineGroup/utils.spec.js
Available hours returns incorrect data when there are denied or cancelled reservations.
Closes #532.
=> Use opening hours instead of available hours

server/Html.js
More info about the polyfill [here](https://www.npmjs.com/package/intl#intljs-and-ft-polyfill-service).
Closes #534.
=> Add intl polyfill for older browsers

app/shared/availability-view/TimelineGroups/TimelineGroups.js
=> Fix IE11 error

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/shared/modals/reservation-success/ReservationSuccessModal.js, app/shared/modals/reservation-success/ReservationSuccessModal.spec.js
English and Swedish translations might change in the future.
Closes #545.
=> Improve reservation success modal button text

app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.spec.js, app/shared/availability-view/availability-view.less
=> Add comments badge to reservation

server/auth/index.js
=> Prolong max session age to 9 hours

app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js, app/shared/availability-view/availability-view.less
=> Add reservation length to reservationSlot

app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.spec.js, app/shared/availability-view/availability-view.less
=> Change backgroud for reservations with requested state

app/pages/admin-resources/AdminResourcesPage.js, app/pages/admin-resources/AdminResourcesPage.spec.js
=> Fetch resources in adminResourcesPage if location changes

app/pages/PageWrapper.js, app/pages/PageWrapper.spec.js, app/pages/admin-resources/AdminResourcesPage.js, app/pages/admin-resources/AdminResourcesPage.spec.js
=> Make "Omat tilat" fluid

app/shared/availability-view/availability-view.less
=> Fix sticky z-index (Refs #578)

config/make-karma-config.js
Shows diffs of expected and actual values on failed tests.
=> Improve karma test configs

app/shared/recurring-reservation-controls/RecurringReservationControls.js, app/shared/recurring-reservation-controls/RecurringReservationControls.spec.js
=> Remove week day from recurring reservation controls

app/shared/resource-calendar/ResourceCalendar.js, app/shared/resource-calendar/ResourceCalendar.spec.js
=> Fix disabled and selected days on ResourceCalendar

app/shared/availability-view/availability-view.less
=> Fix availability datepicker styles

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.js, app/shared/availability-view/Sidebar/GroupInfo/ResourceInfo/ResourceInfoContainer.spec.js, app/shared/availability-view/availability-view.less, app/state/reducers/ui/adminResourcesPageReducer.js, app/state/reducers/ui/adminResourcesPageReducer.spec.js
=> Show favorited unpublished resources on admin view

app/i18n/messages/en.json, app/shared/compact-reservation-list/CompactReservationList.js, app/shared/compact-reservation-list/CompactReservationList.spec.js, app/shared/compact-reservation-list/compact-reservation-list.less, app/shared/reservation-confirmation/ConfirmReservationModal.js, app/shared/reservation-confirmation/ConfirmReservationModal.spec.js, app/shared/reservation-confirmation/ReservationConfirmationContainer.js, app/shared/reservation-confirmation/ReservationConfirmationContainer.spec.js, app/state/recurringReservations.js, app/state/recurringReservations.spec.js
Closes #571
I've updated the numberOfOcurrencesLabel english label so it's easier to understand. Should I change the finnish and swedish labels?
=> Allow to remove times from recurring reservation

app/shared/availability-view/availability-view.less
=> Fix current time visibility on admin resources

app/shared/resource-map/MapContainer.js, app/shared/resource-map/MapContainer.spec.js, app/shared/resource-map/Marker.js, app/shared/resource-map/Marker.spec.js, app/shared/resource-map/mapSelector.js, app/shared/resource-map/mapSelector.spec.js
=> Group resources markers by unit and show number

package.json, server/Html.js
=> Add Font Awesome for more awesome icons

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/search/controls/DatePickerControl.js, app/pages/search/controls/DatePickerControl.spec.js, app/pages/search/controls/SearchControlsContainer.js, app/pages/search/controls/SearchControlsContainer.spec.js, app/pages/search/controls/_search-controls.scss
=> Change DatePickerControl in SearchControls

app/pages/resource/resource-info/ResourceInfo.js, app/pages/resource/resource-info/ResourceInfo.spec.js
=> Order resource images in ResourceInfo

app/pages/resource/resource-info/_resource-info.scss
=> Fix images wrapper sizes

app/pages/search/controls/SearchControlsContainer.js
Remove automatic search from search text box.
Refs #664.
=> Don't search automatically on search text change

app/shared/footer/Footer.js, app/shared/footer/Footer.spec.js, app/shared/footer/FooterContent.js, app/shared/footer/FooterContent.spec.js, app/shared/navbar/Navbar.js, app/shared/navbar/Navbar.spec.js, app/shared/side-navbar/SideNavbar.js, app/shared/side-navbar/SideNavbar.spec.js
=> Closes Navbar on NavItem click

app/assets/styles/_application-variables.scss, app/assets/styles/_react-select.scss, app/shared/date-picker/_date-picker.scss, app/shared/recurring-reservation-controls/_recurring-reservation-controls.scss
=> Fix styles on recurring reservation controls

app/shared/sidebar/Sidebar.js, app/shared/sidebar/Sidebar.spec.js
=> Change touch prop on Sidebar to false

app/shared/resource-map/Marker.js, app/shared/resource-map/Marker.spec.js, app/shared/resource-map/_map.scss
=> Add number of resources to marker's icon

app/shared/resource-card/_resource-card.scss
=> Fix resource card image not showing in Safari

app/shared/side-navbar/_side-navbar.scss
=> Fix navbar overlaps in safari

app/pages/resource/_resource-page.scss, app/pages/resource/resource-info/_image-carousel.scss
=> Remove side margins in resource page image

app/shared/side-navbar/_side-navbar.scss
=> Fix SideNavBar scroll bar

app/pages/resource/reservation-calendar/time-slots/_time-slots.scss
=> Change time-slots margin from % to px

app/pages/search/controls/_search-controls.scss
=> Center calendar number in search date picker

app/pages/search/controls/_search-controls.scss
=> Fix huge search box cursor in safari

app/assets/styles/_application-variables.scss, app/assets/styles/_layout.scss, app/pages/resource/_resource-page.scss
=> Fix container layout width in desktop

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/home/intro/HomeIntro.js
New link to frontpage, link points to new UI test site.
=> Added new link to frontpage.

app/shared/resource-card/ResourceCard.js, app/shared/resource-card/ResourceCard.spec.js
=> Search by type on resourceCard type click

app/pages/search/searchPageSelector.js, app/pages/search/searchPageSelector.spec.js, app/shared/resource-card/ResourceCard.js
=> Order resources by distance in search page

app/assets/styles/customization/espoo/customization.scss, app/pages/AppContainer.js, package.json
=> Modals espoo header image

app/assets/styles/customization/espoo/customization.scss, app/assets/styles/customization/vantaa/customization.scss
=> Fix Espoo and Vantaa customization colors (#772)

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/resource/ResourcePage.js, app/pages/resource/ResourcePage.spec.js, app/pages/resource/_resource-page.scss
=> Link back to search results on resource page

app/pages/search/controls/DatePickerControl.js, app/pages/search/controls/DatePickerControl.spec.js, app/pages/search/controls/PeopleCapacityControl.js, app/pages/search/controls/PeopleCapacityControl.spec.js, app/pages/search/controls/PositionControl.js, app/pages/search/controls/PositionControl.spec.js, app/pages/search/controls/PurposeControl.js, app/pages/search/controls/PurposeControl.spec.js, app/pages/search/controls/SearchControlOverlay.js, app/pages/search/controls/SearchControlOverlay.spec.js, app/pages/search/controls/_search-controls.scss
=> Search filter dropdowns

app/pages/search/SearchPage.js, app/pages/search/SearchPage.spec.js, app/pages/search/results/SearchResults.js, app/pages/search/results/SearchResults.spec.js, app/shared/resource-card/ResourceCard.js, app/shared/resource-card/ResourceCard.spec.js, app/shared/resource-list/ResourceList.js, app/shared/resource-list/ResourceList.spec.js
=> Scrolls to previous position when returning to search results

app/pages/resource/resource-info/ResourceInfo.js, app/pages/resource/resource-info/ResourceInfo.spec.js
Removed terms and conditions paragraph from resource page.
=> Removed terms and conditions paragraph from resource page.

app/pages/resource/reservation-calendar/time-slots/_time-slots.scss, app/shared/resource-calendar/_resource-calendar.scss
This PR has temporary fix for reservation calendar bug in desktop version.
=> Fixed resource page reservation calendar bug

app/pages/resource/ResourcePage.js
Renamed the external calendar url field to correspond changes in Respa.
=> Renamed external calendar url to external reservation url

app/pages/resource/reservation-info/ReservationInfo.js, app/pages/resource/reservation-info/ReservationInfo.spec.js, app/pages/resource/resource-info/ResourceInfo.js, app/pages/resource/resource-info/ResourceInfo.spec.js, app/shared/wrapped-text/WrappedText.js, app/shared/wrapped-text/WrappedText.spec.js
- Add openLinksInNewTab prop for WrappedText 
- Use the prop with resource info, reservation info
- Add the target attribute to additional info links
=> Open resource info, reservation info, additional info links in new tabs

app/i18n/messages/sv.json
=> Fix translation for ResourceCard.peopleCapacity

app/pages/resource/resource-info/_resource-info.scss, config/webpack.production.js
- Fix resource image sizes on IE
- Disable SVG optimizations with css-loader>cssnano>svgo in production builds to fix background svg images with IE11
=> Fix IE bugs

app/pages/resource/reservation-calendar/ReservationCalendarContainer.js, app/pages/resource/reservation-calendar/_reservation-calendar.scss, app/pages/resource/reservation-calendar/time-slots/_time-slots.scss, app/pages/resource/resource-info/_resource-info.scss
- Fix extra spacing between reservation calendar and reservation summary
- Fix resource calendar being placed below footer when using the calendar far in the future
=> Calendar spacing fixes

app/pages/resource/ResourcePage.js, app/pages/resource/resource-header/ResourceHeader.js, app/pages/resource/resource-header/ResourceHeader.spec.js, app/pages/resource/resource-map-info/ResourceMapInfo.js, app/pages/resource/resource-map-info/ResourceMapInfo.spec.js, app/pages/resource/resource-map-info/_resource-map-info.scss
Move the distance information from resource map info to resource header
=> Move distance info to resource header

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/resource/reservation-calendar/time-slots/TimeSlot.js, app/pages/resource/reservation-calendar/time-slots/TimeSlot.spec.js, app/pages/resource/reservation-calendar/time-slots/TimeSlots.js, app/pages/resource/reservation-calendar/utils.js, app/shared/_shared.scss, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/ReservationSlot.spec.js, app/shared/availability-view/_availability-view.scss, app/shared/reservation-popover/ReservationPopover.js, app/shared/reservation-popover/ReservationPopover.spec.js, app/shared/reservation-popover/_reservation-popover.scss, app/shared/reservation-popover/index.js, app/utils/fixtures/TimeSlot.js
- Separate reservation info popup implementation from `ReservationSlot` to a new `ReservationPopover` component
- Reuse component in `TimeSlots`
- Remove moment.js use from loops in `TimeSlots`, `TimeSlot` to improve performance when mouseovering
=> Add reservation info popup to reservation calendar

app/pages/search/SearchPage.js, app/pages/search/SearchPage.spec.js, app/pages/search/controls/SearchControlsContainer.js
Feature does not work correctly and functionality is unwanted in any case; removed.
=> Remove scrolling to search results on search button click

app/assets/styles/customization/espoo/customization.scss, app/assets/styles/customization/vantaa/customization.scss, app/pages/home/HomePage.js, app/pages/home/HomePage.spec.js, app/pages/home/_home-page.scss
- Wrap div in big React-router Link component
- Use 12 col in mobile mode.
=> [Feature] Make homepage banner clickable

app/assets/styles/_react-select.scss, app/pages/search/controls/SearchControlsContainer.js
- Fix `SelectControl` have different height when `has_value`
- Add better filter layout
=> [Hotfix] Filter layout fix

README.md, app/state/reducers/notificationsReducer.js, app/state/reducers/notificationsReducer.spec.js, package.json, yarn.lock
`[...state, Object.assign({})]` 
Trying to spread an Immutable object with normal object is wrong and cause the app to crash when trying to make array
Maintainance job: Upgrade `seamless-immutable` to latest, tweak README and lock node version on `package.json`
=> Fix reservation cancel modal UI get stuck

.gitignore, app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/search/controls/SelectControl.js, app/pages/search/controls/SelectControl.spec.js
Did not bother bothering someone for actual translations, so those are my best guess at what they could be.
=> VAR-51 | Translate SelectControl noOptionsMessage

app/pages/PageWrapper.js, app/pages/resource/ResourcePage.js, app/pages/resource/reservation-calendar/time-slots/TimeSlots.js, app/pages/search/controls/CheckboxControl.js, app/pages/search/results/SearchResultsPaging.js, app/shared/availability-view/TimelineGroups/TimelineGroup/AvailabilityTimeline/Reservation.js, app/shared/favorite-button/FavoriteButton.js, app/shared/label/Label.js, app/shared/resource-card/ResourceCard.js, app/shared/resource-map/MapContainer.js, app/shared/resource-type-filter/ResourceTypeFilterButton.js
https://helsinkisolutionoffice.atlassian.net/browse/VAR-102
=> VAR-102 | Rename all classnames imports to classNames

app/shared/resource-card/ResourceCard.js
This PR should fix the issue VAR-58
=> Fix resource page view position when search result is clicked

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/manage-reservations/ManageReservationsPage.js, app/shared/main-navbar/MainNavbar.js, app/shared/main-navbar/__tests__/MainNavbar.test.js, src/routes.js
This tiny PR adds 'Manage Reservation' link in the page header.
=> VAR-134 | Add manage reservation link in page header

app/pages/manage-reservations/ManageReservationsPage.js, src/domain/reservations/manage/ManageReservations.js, src/routes.js
Nothing special, just relocate new file to `src` to follow new folder structure
=> Relocate manage reservation under src

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json
Just updating to correct translation provided by Samuel.
=> Update correct translation for resource equipment headline

src/common/data/utils.js, src/domain/resource/card/ResourceCard.js
Search page headline and description does not have fallback language currently. This PR adds fallback to available language.
=> VAR-143 | Add fallback to available language in search page headline and desc

app/shared/date-picker/_date-picker.scss, app/shared/recurring-reservation-controls/RecurringReservationControls.js, app/shared/recurring-reservation-controls/_recurring-reservation-controls.scss, app/shared/reservation-confirmation/_confirm-reservation-modal.scss
This PR should fix misalignment on repeat reservation date picker and minor layout improvement.
=> [Hotfix] VAR-147 | Fix misalignment on repeat reservation date picker

CHANGELOG.md, app/pages/reservation/ReservationPage.js, app/pages/reservation/__tests__/ReservationPage.test.js, app/shared/compact-reservation-list/CompactReservationList.js, app/shared/recurring-reservation-controls/RecurringReservationControls.js, app/shared/recurring-reservation-controls/__tests__/RecurringReservationControls.test.js, app/shared/recurring-reservation-controls/connectRecurringReservationControls.js
This PR is just a minor fix to check permission level. Now, recurring reservation tool is shown only to users who have admin right.
=> VAR-36 | Render recurring reservation tool only to user with admin right

CHANGELOG.md, src/domain/reservation/manage/page/ManageReservationsPage.js, src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
As requested from PO
Check ticket description.
=> VAR-192 | Add can_modify as default of `show_only` filter

package.json, yarn.lock
5.2.0 had a bug where it could crash the app (Internal error: too much recursion).
More info https://github.com/nfl/react-helmet/issues/441
=> Update react-helmet to 5.2.1

src/domain/reservation/manage/list/ManageReservationsList.js, src/domain/reservation/manage/list/__tests__/__snapshots__/ManageReservationsList.test.js.snap, src/domain/reservation/manage/list/_manageReservationsList.scss, src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
Say something if this is dumb idea
=> VAR-191 | Wrap empty value cell with -

CHANGELOG.md, app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, src/common/calendar/__tests__/TimePickerCalendar.test.js, src/domain/resource/reservationCalendar/ResourceReservationCalendar.js, src/domain/resource/reservationCalendar/__tests__/__snapshots__/ResourceReservationCalendar.test.js.snap, src/domain/resource/reservationCalendar/_resourceReservationCalendar.scss
For anonymous users, instead of showing a "Reserve" button that leads to the front page via a login page, we show a help text and login button that leads back to the resource page.
=> VAR-190 | Improve resource page usability for anonymous users

app/pages/browser-warning/BrowserWarning.js, app/shared/form-fields/TermsField.js, app/shared/modals/reservation-info/ReservationInfoModal.js, app/shared/reservation-popover/ReservationPopover.js
Fixing eslint for Windows users.
=> Fix eslint for windows

CHANGELOG.md, app/pages/reservation/reservation-information/__tests__/ReservationInformation.test.js, app/pages/resource/_resource-page.scss, app/pages/resource/resource-header/_resource-header.scss, app/pages/resource/resource-info/_resource-info.scss, app/shared/resource-calendar/_resource-calendar.scss, src/common/calendar/TimePickerCalendar.js, src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap, src/common/calendar/_timePickerCalendar.scss
- Add custom header as well as styling only for mobile.
- Fix some broken styling on mobiles
=> VAR-205 | Daily/ Weekly view for mobile

CHANGELOG.md, app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/resource/resource-info/ResourceInfo.js, app/pages/resource/resource-info/_resource-info.scss
Removed overflow settings and replaced ResourceInfo URL with text. Added translations for "website".
=> VAR-216 | Resourcepage scrollbars

CHANGELOG.md, app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/resource/ResourcePage.js, src/common/calendar/TimePickerCalendar.js, src/common/calendar/__tests__/__snapshots__/TimePickerCalendar.test.js.snap, src/common/calendar/_timePickerCalendar.scss
Changed fullCalendar buttons to custom buttons and added translations for "today". If resource has reservableBefore, DatePicker will disable days after that.
=> VAR- 224 | Can't change week.

CHANGELOG.md, app/shared/availability-view/_availability-view.scss, app/shared/availability-view/timeline-groups/timeline-group/TimelineGroup.js, app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/AvailabilityTimeline.js, app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/ReservationSlot.js, app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/__tests__/ReservationSlot.test.js
My premises now gets slotSize from resource.
=> VAR - 238 | Change min slot size in my premises

CHANGELOG.md, app/pages/reservation/ReservationPage.js, app/pages/reservation/reservation-information/ReservationInformation.js, app/pages/reservation/reservation-information/ReservationInformationForm.js, app/pages/reservation/reservation-information/__tests__/ReservationInformation.test.js, app/pages/reservation/reservation-information/_reservation-information.scss, app/shared/form-fields/TermsField.js, app/shared/form-fields/__tests__/TermsField.test.js
Replaced modals with boxes that hold terms of service texts.
=> VAR - 237 | Display payment and resource terms of service

CHANGELOG.md, app/pages/admin-resources/AdminResourcesPage.js, app/pages/admin-resources/__tests__/AdminResourcesPage.test.js, app/pages/admin-resources/__tests__/adminResourcesPageSelector.test.js, app/pages/admin-resources/adminResourcesPageSelector.js, app/shared/availability-view/_availability-view.scss, app/shared/availability-view/sidebar/group-info/resource-info/ResourceInfoContainer.js, app/shared/availability-view/sidebar/group-info/resource-info/__tests__/ResourceInfoContainer.test.js
Added premise name text and sorted resources based on that.
=> VAR - 253 | Display premise location text in my premises page

package.json, src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
Updated package.json version to 0.8.0.
=> VAR - 249 | Update footer version

CHANGELOG.md, app/pages/reservation/ReservationPage.js, app/pages/reservation/reservation-confirmation/ReservationConfirmation.js, app/pages/reservation/reservation-confirmation/__tests__/ReservationConfirmation.test.js, app/pages/reservation/reservation-information/InternalReservationFields.js, src/domain/reservation/manage/page/ManageReservationsPage.js
Navigation will now return user to correct pages in following scenarios:
- Editing existing reservation and cancelling process.
- Editing existing reservation and saving changes.
- While editing and refreshing page.
When editing reservation form is filled with initial values.
=> VAR - 198 | Wrong view after editing reservation

CHANGELOG.md, app/shared/availability-view/DateSelector.js, app/shared/availability-view/_availability-view.scss, src/domain/search/filters/SearchFilters.js, src/domain/search/filters/__tests__/__snapshots__/SearchFilters.test.js.snap, src/domain/search/filters/_searchFilters.scss, src/domain/search/filters/filter/_dateFilter.scss
Added today buttons to search and my premise pages.
=> VAR - 37 | Today buttons

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/pages/AppContainer.js, app/pages/__tests__/AppContainer.test.js, app/shared/_shared.scss, app/shared/accessibility-shortcuts/AccessibilityShortcuts.js, app/shared/accessibility-shortcuts/__tests__/AccessibilityShortcuts.test.js, app/shared/accessibility-shortcuts/_accessibility-shortcuts.scss
This change is part of the accessibility changelist. It resolves VAR-283.
Relevant commit in Turku's repo
https://github.com/codepointtku/varaamo/commit/2f192dea832ec9f586a8aece40c71f5e176cb942#diff-4bf6d7c1778bc725f9bbcd22e36bc8cd
=> VAR-238 | Add skip to content link

app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/Reservation.js, app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/__tests__/Reservation.test.js, src/domain/resource/constants.js
Price should only show for resources that implicitly support online
payment.
Check
https://helsinkisolutionoffice.atlassian.net/browse/VAR-321?atlOrigin=eyJpIjoiYjgxMWZmODFiMGU4NDY2Yjg4NjMyYjM2ZmYzYjg1NjQiLCJwIjoiaiJ9
for reproduction instructions.
=> VAR-321 | Fix price for resources that don't support payment

app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, app/shared/availability-view/timeline-groups/timeline-group/availability-timeline/Reservation.js, app/shared/modals/reservation-cancel/ReservationCancelModalContainer.js, app/shared/modals/reservation-cancel/__tests__/ReservationCancelModalContainer.test.js, app/shared/modals/reservation-cancel/__tests__/__snapshots__/ReservationCancelModalContainer.test.js.snap, src/domain/resource/__tests__/utils.test.js, src/domain/resource/utils.js
Varaamo knows with some certainty which reservations are "online" reservations. In those cases, display a custom translation message.
=> VAR-378 | Use custom cancellation message for online reservations

src/common/notificator/user/_userNotificator.scss
=> VAR-393 | Fix notification overflowing with long strings

app/assets/styles/_application-variables.scss, app/i18n/messages/en.json, app/i18n/messages/fi.json, app/i18n/messages/sv.json, src/common/_common.scss, src/common/date-range/DateRangePicker.js, src/common/date-range/__tests__/DateRangePicker.test.js, src/common/date-range/__tests__/__snapshots__/DateRangePicker.test.js.snap, src/common/date-range/__tests__/utils.test.js, src/common/date-range/_dateRangePicker.scss, src/common/date-range/legend/DateRangeLegend.js, src/common/date-range/legend/__tests__/DateRangeLegend.test.js, src/common/date-range/legend/__tests__/__snapshots__/DateRangeLegend.test.js.snap, src/common/date-range/legend/_dateRangeLegend.scss, src/common/date-range/summary/DateRangeSummary.js, src/common/date-range/summary/__tests__/DateRangeSummary.test.js, src/common/date-range/summary/__tests__/__snapshots__/DateRangeSummary.test.js.snap, src/common/date-range/summary/_dateRangeSummary.scss, src/common/date-range/utils.js
Adds a component for selection of date ranges to reserve.
[VAR-419](https://helsinkisolutionoffice.atlassian.net/browse/VAR-419)
- `src/common/date-range/__tests__/DateRangePicker.test.js`
- `src/common/date-range/__tests__/utils.test.js`
- `src/common/date-range/legend/__tests__/DateRangeLegend.test.js`
- `src/common/date-range/summary/__tests__/DateRangeSummary.test.js`
As the project does not use storybook, you will need to manually add the component somewhere in the page. Here's an example I used while developing the component:
```
<DateRangePicker
endingTime={{ hours: 11, min: 0 }}
fullDay={false}
maxDays={7}
minDays={3}
openingPeriods={[
{ from: new Date(2020, 5), to: new Date(2020, 8, 17) },
{ from: new Date(2020, 8, 20), to: new Date(2021, 1) },
]} …
```
=> VAR-419 | Implement DateRangePicker component

app/i18n/messages/en.json, app/i18n/messages/fi.json, src/common/date-range/__tests__/utils.test.js, src/common/date-range/_dateRangePicker.scss, src/common/date-range/utils.js
- Fixes translations displayed for overlapping and unavailable reservations
- Adds missing styles for overnight reservations
- Makes date range validators inclusive
=> Fix DateRangePicker issues

app/shared/resource-calendar/__tests__/ResourceCalendar.test.js
=> Fix failing tests

app/shared/resource-calendar/__tests__/ResourceCalendar.test.js, src/common/notificator/user/_userNotificator.scss
Enlarge the font in user notification bar of type danger.
https://helsinkisolutionoffice.atlassian.net/browse/VAR-453
=> VAR-453 enlarge font in `danger` notification

package.json, src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
=> Change release version

package.json, server/Html.js, src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
- update cookie configuration
- pepare for release
=> TILA-1368 cookie consent #2

package.json, src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap, src/domain/header/MainNavbar.js, src/domain/header/__tests__/MainNavbar.test.js
=> fix: respa admin url link
