City-of-Helsinki/varaamo

- app/actions/resourceActions.js
- app/components/search-page/SearchResult.js
- app/components/search-page/SearchResults.js
- app/components/search-page/__tests__/SearchResult.spec.js
- app/components/search-page/__tests__/SearchResults.spec.js
- app/containers/ResourcePage.js
- app/containers/SearchPage.js
- app/containers/__tests__/ResourcePage.spec.js
- app/containers/__tests__/SearchPage.spec.js
- app/reducers/__tests__/resources.spec.js
- app/reducers/__tests__/search.spec.js
- app/reducers/__tests__/units.spec.js
- app/reducers/resources.js
- app/reducers/search.js
- app/reducers/units.js
- app/selectors/__tests__/resourcePageSelectors.spec.js
- app/selectors/__tests__/searchPageSelectors.spec.js
- app/selectors/resourcePageSelectors.js
- app/selectors/searchPageSelectors.js
- package.json
Switches the codebase to use seamless-immutable instead of immutable-js for immutable data structures.
The many benefits are listed in #19.
Closes #19.
> Switch to using seamless-immutable

- app/actions/resourceActions.js
- app/utils/APIUtils.js
- app/utils/__tests__/APIUtils.spec.js
- package.json
No need to use a fork anymore to camelize keys.
The version 0.6.0 provides an option for a transform function for transforming the response data before it gets to reducers.
Refs #12.
> Update to latest version of redux-api-middleware

- app/actions/purposeActions.js
- app/actions/reservationActions.js
- app/actions/resourceActions.js
- app/actions/unitActions.js
- app/constants/AppConstants.js
- app/utils/APIUtils.js
- app/utils/__tests__/APIUtils.spec.js
In Chrome the API calls were working without specifying
"Accept" and "Content-Type" headers as "application/json".
However API calls in Firefox were not working correctly.
This commit fixes the issue.
Closes #51.
> Explicitly specify headers in API calls

- app/utils/DataUtils.js
- app/utils/__tests__/DataUtils.spec.js
- package.json
Non reserved slots that are in the past should not be counted
to as available time.
Closes #68.
> Use current time to calculate available hours

- package.json
Updates seamless-immutable to version 4.0.2
This update gives us automatic errors on development
whenever we try to mutate an immutable object.
Makes doing mutations by accident a lot harder.
> Update seamless-immutable to latest version

- app/components/reservation/ReservationsTableRow.js
Make the edit buttons link to correct reservation date on my reservations page.
Refs #90 and #95.
> Make my reservations edit links use correct date

- package.json
This PR removes babel-preset packages that are needed only after we update to babel version 6.
> Remove unneeded babel-presets from packages

- config/webpack.development.js
The opening new window is a bit annoying. Devtools
are now disabled by default before we get the new version
of them on the project.
> Disable devtools on development on default

- app/assets/styles/app.less
- app/assets/styles/resource-page.less
- app/containers/ResourcePage.js
This PR locates the resource page reserve button under the location text and makes it expand to the whole width of the screen on mobile screen sizes.
Closes #117.
> Improve resource reserve button mobile styles

- app/containers/ReservationForm.js
This PR doesn't prevent user from splitting a reservation into multiple reservations in the edit mode, but makes it pretty sure that all requests will proceed without errors.
This is very hacky and not bulletproof but use cases where user splits
one reservation into multiple reservations should be pretty rare.
In the future the timeout should be replaced by something sequential.
The timeout allows the PUT request to go through first and
possibly free previously reserved time slots, that might be
needed in the POST requests.
Closes #147.
> Make sure PUT request goes through before POSTs

- app/components/search/SearchFilters.js
- app/components/search/SearchInput.js
- app/components/search/__tests__/SearchInput.spec.js
Makes the UI more clean and does not restrict user as much.
Closes #165.
> Remove unneeded input placeholders

- app/actions/reservationActions.js
- app/utils/APIUtils.js
- app/utils/__tests__/APIUtils.spec.js
Include the Authorization header to all API calls if user is logged in.
Closes #176.
> Include Authorization header in all API requests

- app/constants/AppConstants.js
In the pilot version of the service the Accept-Language is always "fi".
Closes #188.
> Add Accept-Language header to all API requests

- app/components/reservation/ReservationInfo.js
- app/containers/ReservationPage.js
- app/containers/__tests__/ReservationPage.spec.js
This PR:
- Adds max reservations per user count.
- Makes adding new info about reservating easier in the future.
Closes #197.
> Move reservation info into own component

- app/containers/SearchPage.js
If url contains search parameters always fetch search results when component mounts.
This fixes the issue in #158.
Closes #158.
> Fetch search results always on mount

- app/components/search/SearchResult.js
- app/containers/ReservationPage.js
- app/containers/ResourcePage.js
- app/containers/__tests__/ReservationPage.spec.js
- app/containers/__tests__/ResourcePage.spec.js
- app/selectors/containers/__tests__/resourcePageSelector.spec.js
- app/selectors/containers/resourcePageSelector.js
Allows user to switch between search, resource and reservation
pages without losing the chosen date.
Closes #224.
> Store date in url in resource page

- app/assets/styles/reservations-list.less
- app/components/reservation/ReservationControls.js
- app/components/reservation/ReservationsListItem.js
- app/components/reservation/__tests__/ReservationControls.spec.js
- app/components/reservation/__tests__/ReservationsListItem.spec.js
- app/constants/AppConstants.js
- app/containers/ReservationCancelModal.js
- app/containers/__tests__/ReservationCancelModal.spec.js
- app/selectors/__tests__/sortedReservationsSelector.spec.js
- app/selectors/sortedReservationsSelector.js
- app/utils/DataUtils.js
This PR makes the UI use real reservation states. Previously before API had support for preliminary reservations, the states were created in the UI for demo purposes.
Closes #257.
> Use real reservation states

- app/containers/UserReservationsPage.js
- app/containers/__tests__/UserReservationsPage.spec.js
Moves preliminary reservations list before regular reservations list.
Closes #264.
> Switch reservations lists order in admin view

- app/components/reservation/TimeSlots.js
This is needed for admins who have more information on the
calendar.
It also makes the reservation form not expand more than the screen width.
Closes #272.
> Make reservation calendar responsive

- app/actions/reservationActions.js
- app/components/reservation/ConfirmReservationModal.js
- app/constants/AppConstants.js
- app/containers/ReservationForm.js
- app/containers/__tests__/ReservationForm.spec.js
This PR:
- Renders all reservation form fields by default for preliminary reservations.
- Only sends data to backend from fields that have non-empty strings.
- Adds some max-length validators to the form fields.
Closes #275.
> Render all reservation form fields by default

- package.json
Gets rid of unnecessary depracation warnings in latest Chrome
dev console.
> Update webpack to version 1.13.0

- app/store/configureStore.js
This makes it lot easier to follow in the console what actions are fired.
> Make logged actions collapsed by default

- app/containers/UserReservationsPage.js
- app/containers/__tests__/UserReservationsPage.spec.js
- app/selectors/containers/__tests__/userReservationsPageSelector.spec.js
- app/selectors/containers/userReservationsPageSelector.js
This PR:
- Shows all reservations in user reservation page an admin can approve.
- Makes sure the page is only rendered once it's known whether user is an admin or not.
Closes #274.
> Show reservations admin can approve in list

- app/containers/UserReservationsPage.js
- app/containers/__tests__/UserReservationsPage.spec.js
- app/selectors/containers/userReservationsPageSelector.js
Previous implementation did not consider cases where resources were
already loaded and it was known on mount whether user is an admin or not.
Refs #274.
> Always show can approve reservations for admin

- app/components/reservation/ReservationControls.js
- app/components/reservation/__tests__/ReservationControls.spec.js
Only admins with staff permissions should be able to confirm and decline
preliminary reservations.
Closes #304.
> Fix admin confirm and decline rights

- app/utils/DataUtils.js
- app/utils/__tests__/DataUtils.spec.js
Makes sure cancelled reservations are not used in available time
calculations.
Fixes #323.
> Fix cancelled reservations in time calculations

- app/utils/DataUtils.js
- app/utils/__tests__/DataUtils.spec.js
If provided shows the unit municipality in addresses. Otherwise uses Helsinki as the default city.
> Use unit.municipality in addresses

- app/reducers/__tests__/reservationsReducer.spec.js
- app/reducers/reservationsReducer.js
Reservation PUT requests where causing the edited reservation to be put
into list of reservations to show in the info modal.
Closes #401.
> Fix wrong info in reservation info modal issue

- app/screens/shared/resource-list/ResourceListItem.js
- app/screens/shared/resource-list/ResourceListItem.spec.js
Making the whole box a link is not possible since it already contains the reservation button that is another link to reservation page.
Closes #414.
> Make the image of resource list item a link

- app/pages/search/controls/SearchControlsContainer.js
- app/shared/comment-form/CommentForm.js
- app/shared/comment-form/CommentForm.spec.js
- app/shared/modals/reservation-info/ReservationInfoModalContainer.js
Submit button inside a comment form was making the page refresh on Firefox and IE.
Closes #490.
> Fix comment modal on Firefox and IE

- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- app/shared/modals/reservation-info/ReservationInfoModalContainer.js
- app/shared/modals/reservation-info/ReservationInfoModalContainer.spec.js
- app/state/reducers/ui/reservationInfoModalReducer.js
- app/state/reducers/ui/reservationInfoModalReducer.spec.js
Adds cancel button to reservation info modal.
Opening another modal on top of the info modal might not be optimal
but was the quickest solution at this point.
Closes #506.
> Add cancel button to reservation info modal

- app/shared/modals/reservation-info/ReservationEditForm.js
- app/shared/modals/reservation-info/ReservationEditForm.spec.js
- app/shared/modals/reservation-info/ReservationInfoModal.js
Shows edit button only if reservation has editable fields.
This is quick fix before reservation times become editable. Then
all reservations will have editable fields.
Closes #550.
> Show edit button only when it makes sense

- app/pages/user-reservations/reservation-filters/AdminReservationFilters.js
Small improvements to admin reservation filters functionality. (I noticed these while improving selects in #561)
- Removes searchability. There are only couple of options and without
searching the select is less confusing.
- Removes possibility for clearing the select value completely.
> Improve admin reservation filters

- app/pages/resource/reservation-calendar/reservationCalendarSelector.js
At least resource.availableHours can be null and a regular filter will fail
with that. The lodash filter will just return an empty array if null is
filtered.
Closes #593.
> Fix edit button on own resources page

- app/shared/resource-calendar/resourceCalendarSelector.js
When moving from own reservations to resource page, the state contained reservations for the resource for days for which there was no opening hours. This was causing an error in the resourceCalendarSelector.
Refs #593.
> Fix edit button on own reservations page

- app/shared/availability-view/availability-view.less
Reduce popover z-index properties for reservations so popovers stay
behind modals.
Closes #602 .
> Reduce popover z-index properties for reservations

- app/shared/availability-view/availability-view.less
A quick hotfix before we get the new day picker to the availability view.
The default date-picker calendar icon works well in closing and opening
the calendar. This commit makes that icon invisible and adds an expand icon
on top of that. The icon direction changes when the calendar is open to make
it cleared that the icon can be used to close the calendar.
Closes #607.
> Improve availability view expand icon

- app/pages/search/SearchPage.js
- app/pages/search/SearchPage.spec.js
Don't fetch search results again when getting back to search page from resource page.
Refs #664.
> Feature/664 search improvements - part 2

- app/shared/side-navbar/SideNavbar.js
- app/shared/side-navbar/SideNavbar.spec.js
- app/shared/sidebar/Sidebar.js
This PR:
- Makes the navbar open on initial page load by default.
- Makes sure the navbar never expands the whole screen even on smaller mobile devices.
Refs #701.
> Feature/701 more informative home page - part 1

- app/state/reducers/dataReducer.js
- app/state/reducers/dataReducer.spec.js
Deep merging was keeping fields like "distance" on the resource data.
> Avoid deep merging on SEARCH_RESULTS_GET_SUCCESS

- app/shared/date-picker/DatePicker.js
- app/shared/date-picker/_date-picker.scss
- app/shared/recurring-reservation-controls/RecurringReservationControls.js
- Add `positionRight` prop for DatePicker to optionally right-align calendar picker and corresponding input
-  Use the prop in RecurringReservationControls
> Adjust positioning for date picker 

- app/shared/resource-card/ResourceAvailability.js
- app/shared/resource-card/ResourceAvailability.spec.js
Fix for #820 
- Do not show reservation status if resource has an external reservation system
> If resource has external reservation url then hide status

- app/pages/resource/ResourcePage.js
- app/pages/resource/resource-header/ResourceHeader.js
- app/pages/resource/resource-header/ResourceHeader.spec.js
- app/shared/resource-card/ResourceCard.js
- app/shared/resource-card/ResourceCard.spec.js
- app/utils/__tests__/resourceUtils.spec.js
- app/utils/resourceUtils.js
- Add `showBackButton` prop to ResourceHeader
- ResourceCard will pass `fromSearchResults` in Link's location state for ResourcePage to determine if the back button should be shown
> Show resource page back button only when coming from search results page

- app/assets/styles/_react-select.scss
- app/constants/AppConstants.js
- app/i18n/messages/en.json
- app/pages/search/controls/CheckboxControl.js
- app/pages/search/controls/DatePickerControl.js
- app/pages/search/controls/DatePickerControl.spec.js
- app/pages/search/controls/PositionControl.js
- app/pages/search/controls/PositionControl.spec.js
- app/pages/search/controls/SearchControlsContainer.js
- app/pages/search/controls/SearchControlsContainer.spec.js
- app/pages/search/controls/TimeRangeControl.js
- app/pages/search/controls/TimeRangeControl.spec.js
- app/pages/search/controls/_search-controls.scss
- app/state/reducers/ui/searchReducer.js
- app/state/reducers/ui/searchReducer.spec.js
- app/state/selectors/__tests__/uiSearchFiltersSelector.spec.js
- app/state/selectors/__tests__/urlSearchFiltersSelector.spec.js
- app/state/selectors/uiSearchFiltersSelector.js
- app/state/selectors/urlSearchFiltersSelector.js
- app/utils/__tests__/timeUtils.spec.js
- app/utils/searchUtils.js
- app/utils/timeUtils.js
- On search page, after opening Advanced search, always display the time range options, not just after the checkbox is checked
- When the date is changed, do not reset the time range options
- Improvements to time range options getting reset to empty values
- Improvements to visual issues in the search components during varying page widths
> Search time range changes

- app/pages/resource/reservation-calendar/time-slots/TimeSlotPlaceholder.js
- app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
- app/pages/resource/reservation-calendar/time-slots/TimeSlots.spec.js
- app/pages/resource/reservation-calendar/time-slots/_time-slots.scss
- To align times, add a placeholder component to reservation calendar day columns with start time later than earliest start time
- Manage vertical offset for "mobile" 3 day view 
- Take into account days when unit is closed (in time slots, start field: date only, no end field)
> Vertically align time slots in reservation calendar

- app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
- app/pages/resource/reservation-calendar/time-slots/_time-slots.scss
Currently in reservation calendar selected date is not highlighted in any way in the weekly or mobile view. This fixes that.
> Highlight selected date in reservation calendar

- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- app/pages/resource/reservation-info/ReservationInfo.js
Fixes the user being redirected to the front page after logging in via the link in reservation info on the resource page.
> Add missing "next" parameter to resource info login redirect

- app/pages/search/controls/SelectControl.js
- app/pages/search/controls/SelectControl.spec.js
- app/pages/search/controls/TimeRangeControl.js
- app/pages/user-reservations/reservation-filters/AdminReservationFilters.js
- app/shared/recurring-reservation-controls/RecurringReservationControls.js
- app/shared/recurring-reservation-controls/RecurringReservationControls.spec.js
- Add `app-Select` as default className prefix on `SelectControl` component
- Fix deprecated prop on SelectControl on `RecurringReservation`
- Remove `classnames` import when using `SelectControl` component
> [Hotfix] Prepend missing prefix on className, remove deprecated options

- app/pages/search/controls/SearchControlsContainer.js
- app/pages/search/controls/SearchControlsContainer.spec.js
- app/pages/search/controls/SelectControl.js
- app/state/reducers/ui/searchReducer.js
- app/state/selectors/__tests__/urlSearchFiltersSelector.spec.js
- app/state/selectors/urlSearchFiltersSelector.js
This PR should fix : `Reset filters` button should clear filters after it is clicked without needing to click the `Search` button after the `Reset filter` is clicked.
> Fix Reset Filters

- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- app/pages/search/controls/PeopleCapacityControl.js
- app/pages/search/controls/PurposeControl.js
- app/shared/fontawesome-icon/FontAwesomeIcon.js
- app/shared/fontawesome-icon/FontAwesomeIcon.spec.js
- app/shared/fontawesome-icon/index.js
- app/shared/main-navbar/MainNavbar.js
- app/shared/main-navbar/MainNavbar.spec.js
- app/shared/main-navbar/_main-navbar.scss
- package.json
- server/Html.js
- yarn.lock
Add new `Maintenance` tab, `Guide` tab in navbar, for admin only, one redirect to respa admin UI, one  point to gitbook.
Maintenance work: 
- Replace all `react-fontawesome` with `react-fontawesome` from `FontAwesome` author.
- Replace all `react-fontawesome` import with single component.
- Add bold theme for react-fontawesome as request from @SamuelSaarentola
> Navigation links for staff

- app/shared/comment-form/CommentForm.js
- app/shared/comment-form/CommentForm.spec.js
- app/shared/modals/reservation-info/ReservationInfoModal.js
- app/shared/modals/reservation-info/ReservationInfoModal.spec.js
**Hotfix**
React-bootstrap `ref` prop is deprecated and replace with `inputProps`
This issue is causing the comment value undefined, causing the edit issue.
> VAR-34 | Staff comment section is not working

- app/i18n/changeLocale.js
Persisted locale should be save as `se` instead of `sv`
persistLocale function should save `locale` instead of `language`
> VAR-25 | Swedish translations changing to react parameter names

- app/shared/date-picker/DatePicker.js
- app/shared/date-picker/DatePicker.spec.js
`shared/DatePicker` is missing `locale` props to make localization to work
> VAR-40 | My premises date picker is in English on Finnish version

- .travis.yml
- app/i18n/initI18n.js
- app/utils/__tests__/timeUtils.spec.js
- config/jest/setupJest.js
- package.json
- yarn.lock
- Use smaller subset of `moment-timezone`, reduce application build size.
- Use dynamic timezone for varaamo app.
- Make `Travis` environment stick with Finnish timezone to make sure no old test was hurt because of this change.
> VAR-39 | Set varaamo timezone to flexible base on user local timezone

- app/pages/resource/reservation-calendar/time-slots/TimeSlot.js
- app/pages/resource/reservation-calendar/time-slots/TimeSlot.spec.js
- app/state/reducers/ui/reservationsReducer.js
- app/state/reducers/ui/reservationsReducer.spec.js
- app/utils/timeUtils.js
Populated endSlot was equal startSlot + minPeriod, timediff was increased minPeriod + slotSize instead of minPeriod only (due to last slot)
> VAR-76 | Fix the bug of getting one slot extra in timediff.

- app/pages/resource/reservation-calendar/ReservationCalendarContainer.js
- app/pages/resource/reservation-calendar/time-slots/TimeSlot.js
- app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
- app/pages/resource/reservation-calendar/utils.js
- app/pages/resource/reservation-calendar/utils.spec.js
This is temp solution to fix the bug, need refactor further.
> VAR-73 | show warning when select disabled slot by mistake

- app/pages/resource/reservation-calendar/time-slots/TimeSlots.js
When user selected start time slot (`selected.length !== 0`), should not enable this limit on time slot property, causing extending selected timeslot click to trigger the unwanted error
> VAR-73 | disable isUnderMinPeriod check anytime there are selected slot

- app/state/reducers/ui/reservationsReducer.js
- app/utils/__tests__/timeUtils.test.js
- app/utils/reservationUtils.js
- app/utils/timeUtils.js
The old behavior returned an negative number when calling the function with sane arguments (i.e. startTime is before endTime). This fixes the behavior so that the result is a positive number when startTime is before endTime.
> Fix getTimeDiff behavior

- app/pages/resource/resource-info/ResourceInfo.js
This PR is just for minor fix : to show `specific terms` only if it exists in resource page.
> Add condition to show specific terms only if resource have it

- CHANGELOG.md
- app/shared/availability-view/_availability-view.scss
- app/shared/date-picker/_date-picker.scss
- app/shared/recurring-reservation-controls/_recurring-reservation-controls.scss
- package.json
- Almost revert old PR.
- Revert/removal overall border styling
- Give dynamic width only with recurring controls (middle aligned)
> [Hotfix] VAR-159 | Datepicker width getting too small

- server/Html.js
Helsinki Matomo (formely Piwik) is now at the root of the server. Also changes piwik -> matomo, as the product has renamed itself.
The host should be renameable as well, but I wanted the most minimal set of changes.
> Update matomo location

- CHANGELOG.md
- src/domain/reservation/constants.js
- src/domain/reservation/information/ReservationMetadata.js
- src/domain/reservation/information/__tests__/ReservationMetadata.test.js
- src/domain/reservation/information/__tests__/__snapshots__/ReservationMetadata.test.js.snap
- src/domain/reservation/manage/action/ManageReservationsDropdown.js
- src/domain/reservation/manage/action/__tests__/ManageReservationsDropdown.test.js
- src/domain/reservation/manage/action/__tests__/__snapshots__/ManageReservationsDropdown.test.js.snap
- src/domain/reservation/modal/ReservationInformationModal.js
- src/domain/reservation/modal/__tests__/__snapshots__/ReservationInfomationModal.test.js.snap
- Dynamically render reservation metadata fields.
- Add custom function to render custom metadata rows.
- Add supported fields (extract from Respa)
- Trim empty field value, hide those field from rendering.
- Hide reservation action button from user without permissions in manage reservation.
> VAR-181 | Reservation information modal is missing metadata fields

- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- src/common/form/fields/_buttonGroupField.scss
- src/domain/reservation/manage/filters/ManageReservationsFilters.js
- src/domain/reservation/manage/filters/__tests__/__snapshots__/ManageReservationsFilters.test.js.snap
- src/domain/reservation/manage/list/ManageReservationsList.js
- src/domain/reservation/manage/list/__tests__/__snapshots__/ManageReservationsList.test.js.snap
- src/domain/reservation/manage/page/ManageReservationsPage.js
- src/domain/reservation/manage/page/__tests__/ManageReservationsPage.test.js
- src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
- When new filters button selected, show reset filters button.
- Keep button state as internal state, so it will persist as long as user not refresh / unmount page.
Extra:
- Rename `location` to `premise` as request from PO.
- Add extra margin between buttons as request from PO.
> VAR-163 | Add new filters to filter reset button, keep filter state when navigate.

- app/pages/resource/resource-info/ResourceInfo.js
What was happening : 
- Headline title was missing in resource page 
- Headline and equipment title was rendered even when there was no any content inside them.
What this PR fixes :
- Adds the headline title in the resource page
-  Makes condition check to render headline and equipment section only if they have some content. 
Test resource link for this : [https://varaamo.test.hel.ninja/resources/awfkojswli4q](https://varaamo.test.hel.ninja/resources/awfkojswli4q)
> Render headline and equipment with condition check

- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- app/pages/reservation/reservation-information/ReservationInformationForm.js
​Specific terms text can be seen on reservation form. But headline is missing. This information should also be seen or hidden depending if resource is using specific terms. This PR should fix it.
Reference latest comment from : VAR-94
> VAR-94 | Add missing specific terms headlines in the reservation form

- app/pages/reservation/ReservationPage.js
- app/pages/reservation/reservation-confirmation/ReservationConfirmation.js
- app/pages/reservation/reservation-confirmation/_reservation-confirmation.scss
- app/pages/reservation/reservationPageSelector.js
What was happening : 
After the repeated reservations were made, if some of the reservations failed, staff members could not see the list of failed reservations.
This PR should solve the issue VAR-36
> VAR-36 | Display unsuccessful reservation list

- CHANGELOG.md
- src/common/api/client.js
- src/domain/reservation/manage/page/ManageReservationsPage.js
Before this errors from Respa got swallowed and try-catch would not catch any errors.
> VAR-209 | Show errors to staff members if editing of reservations fail

- CHANGELOG.md
- app/pages/user-reservations/reservation-list/__tests__/reservationListSelector.test.js
- app/pages/user-reservations/reservation-list/reservationListSelector.js
- app/state/selectors/__tests__/authSelectors.test.js
- app/state/selectors/authSelectors.js
- src/domain/resource/utils.js
Turns out that we nowadays should decide if a user is an admin for a resource here: 
https://respa.koe.hel.ninja/admin/resources/unitauthorization/
so we're now updating the selector
> VAR-173 | Use resource's userPermissions.isAdmin flag to check if user isStaff

- CHANGELOG.md
- src/common/calendar/TimePickerCalendar.js
- src/domain/resource/utils.js
Instead of checking if timerange startTime is AfterNow to prevent user select slot which already happened -> move `now()` to 1 timeSlot to allow that.
> VAR-206 | Allow to select timeslot which is already happening

- CHANGELOG.md
- src/common/calendar/TimePickerCalendar.js
- FullCalendar import its own moment-timezone instance, override default moment-timezone and initial config which came from `initi18n.js`
- Re-set the value after moment timezone import in calendar will fix the issue.
> VAR-39 | Re-assign default timezone which was removed by fullcalendar moment-timezone

- CHANGELOG.md
- package.json
- src/common/api/client.js
- src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
- src/domain/reservation/manage/page/__tests__/ManageReservationsPage.test.js
- src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
- src/domain/search/__tests__/utils.test.js
- src/domain/search/page/SearchPage.js
- src/domain/search/page/__tests__/SearchPage.test.js
- src/domain/search/page/__tests__/__snapshots__/SearchPage.test.js.snap
- src/domain/search/utils.js
- yarn.lock
Otherwise reservations data under resource will be empty. This is required from respa.
Extra:
Change `passport-helsinki` dependency to install either from `git/https`. People who didnt come from Hki org can fetch and use varaamo (for open-source).
> [Hotfix] VAR-149 | Populate resource fetching with default time range as 1 month.

- CHANGELOG.md
- src/domain/search/page/SearchPage.js
There are no need to fetch `500` page_size of data. Making pagination useless.
Reduce default time-range to 1 week of data to reduce payload to Respa.
> [Hotfix] Reduce Varaamo unit, resource fetchAll page_size and timerange

- CHANGELOG.md
- app/pages/resource/ResourcePage.js
- app/pages/resource/reservation-info/ReservationInfo.js
- app/pages/resource/reservation-info/__tests__/ReservationInfo.test.js
- app/pages/resource/resource-info/ResourceInfo.js
Reordered info blocks on ResourcePage. Moved min period from "Reserve" to "Reservation information".
> VAR - 257 | Reorder and combine blocks

- CHANGELOG.md
- src/domain/search/filters/filter/SelectFilter.js
- src/domain/search/filters/filter/TimeRangeFilter.js
- src/domain/search/filters/filter/__tests__/__snapshots__/TimeRangeFilter.test.js.snap
- src/domain/search/filters/filter/_timeRangeFilter.scss
- src/domain/search/results/_searchListResults.scss
Sort by on search page has enough space so it wont disappear under footer. 
TimeRangeFilter selects are now always shown in disabled state.
> VAR - 213 | Search page dropdown & time range

- server/Html.js
Previously the whole settings object was passed down. However, all of
the settings are not in the UI. Further, some settings may pose a
security threat if they are shared. It's better to explicitly pass down
the settings we need.
> Limit client environment to required settings

- .eslintrc
- app/shared/as-polymorph/AsPolymorph.js
- app/shared/as-polymorph/__tests__/AsPolymorph.test.js
- app/shared/tabbable-nav-dropdown/TabbableNavDropdown.js
- app/shared/tabbable-nav-dropdown/TabbableNavItem.js
- app/shared/tabbable-nav-dropdown/__tests__/TabbableNavDropdown.test.js
- app/shared/tabbable-nav-dropdown/__tests__/TabbableNavItem.test.js
- app/shared/tabbable-nav-dropdown/useDropdownDocumentEvents.js
- package.json
- src/domain/header/TopNavbar.js
- src/domain/header/__tests__/TopNavbar.test.js
- yarn.lock
This change addresses the issue in VAR-282.
I think that the issue was, that the language menu was not accessible with tab.
`react-bootstrap` has navigation components which allow devs to implement dropdown menus. These seem to conform to the `role="menu"` pattern, which was not recommended by the accessibility tester when they operated Turku's version of Varaamo. The explicit reason seems to be: a keyboard user normally navigates the page using tab. `role="menu"`expects the user to navigate using arrow keys (and some other keys). This means that a keyboard user needs to change from tab to arrow keys, which harms the user experience.
The relevant commit on Turku's repository can be found from here:
https://github.com/codepointtku/varaamo/commit/27912924a214d07a7e17079a560cb15f4df42e9e …
> VAR-282 | Make language and sign out menus accessible with tab

- .gitignore
- app/pages/AppContainer.js
- app/pages/__tests__/AppContainer.test.js
Fixes VAR-275.
This PR is part of a set of accessibility improvements brought over from Turku's version of Varaamo.
Screen readers rely on the lang attribute to know the language the page uses.
> VAR-275 | Sync HTML lang attribute with application language

- src/domain/header/MainNavbar.js
- src/domain/header/_main-navbar.scss
Ensures that links and buttons within the main navigation have an
outline when focused.
The home menu link is now focused before the mobile menu toggle button.
Previously this was the other way around which made for a confusing
user experience.
Resolves VAR-284
Relevant commit from Turku's repo
https://github.com/codepointtku/varaamo/commit/b2f7edf619845a2c425537b19d34f167d1e3dbae
> VAR-284 | Fix tab behaviour for mobile navigation

- app/constants/AppConstants.js
- src/domain/search/filters/SearchFilters.js
- src/domain/search/filters/__tests__/SearchFilters.test.js
- src/domain/search/filters/__tests__/__snapshots__/SearchFilters.test.js.snap
- src/domain/search/filters/filter/TimeRangeFilter.js
- src/domain/search/filters/filter/__tests__/TimeRangeFilter.test.js
- src/domain/search/filters/filter/__tests__/__snapshots__/TimeRangeFilter.test.js.snap
I have two commits here of which both fix a similar bug in the search page of Varaamo.
--- 
**Reproducing the bug**
1) Go to search page in Varaamo
2) Refine your search by giving a time range
3) Change your searched date into some other day than today
4) Notice that the results are still shown from today
The test data looks to be quite empty at the moment, so it may be easier to reproduce the bug in the test environment (if you want to reproduce it).
You can select a popular location like Oodi, do a norma search, open the details for something that's reservable and then see when it's booked from its calendar. Then you can use this booked date + time combination to search--you should notice that the reservable item is still being returned in the list.
You can also just look at the values …
> VAR-277 | Fix date filter breaking on any other date than today

- yarn.lock
I have tested this by running `yarn && yarn start` and `yarn build`
The amount of security warnings from `yarn audit` drops a lot - the only ones left are from lodash (both the one that is added specifically and the one that is a dependency of modernizr).
> Security updates for devDependencies

- package.json
- yarn.lock
This newer version of react-toggle removes titles from the svg elements
that are used for communicating current state. VoiceOver would read
these titles out loud harming the user experience.
> VAR-291 | Fix unnecessary title in rect-toggle

- package.json
- yarn.lock
**Upgrades lodash 4.17.11 → 4.17.15**  
* Resolves: https://www.npmjs.com/advisories/1065
* Minor change
**Upgrade serialize-javascript 1.3.0 → 2.1.2**  
* Resolves: https://www.npmjs.com/advisories/1426
* [The way in which we use `serialize` is not impacted by the breaking change](https://github.com/yahoo/serialize-javascript/releases/tag/v2.0.0)
**Upgrade codecov**  
* Resolves: https://www.npmjs.com/advisories/1184
* Minor change
On Fri 14.2 around ~16:00 `yarn audit` returned zero results with these changes.
> VAR-323 | Update dependencies with vulnerabilities

- src/domain/search/mapToggle/SearchMapToggle.js
- src/domain/search/mapToggle/__tests__/SearchMapToggle.test.js
- src/domain/search/mapToggle/__tests__/__snapshots__/SearchMapToggle.test.js.snap
- src/domain/search/mapToggle/_searchMapToggle.scss
These buttons were flagged in the accessibility review because you could not for instance access them with the tab key and they were difficult to understand with a screen reader.
> VAR-289 | Make search map toggle more accessible

- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- src/domain/search/mapToggle/SearchMapToggle.js
- src/domain/search/mapToggle/__tests__/SearchMapToggle.test.js
- src/domain/search/mapToggle/__tests__/__snapshots__/SearchMapToggle.test.js.snap
- src/domain/search/results/SearchListResults.js
- src/domain/search/results/__tests__/SearchListResults.test.js
- src/domain/search/sort/SearchSort.js
- src/domain/search/sort/__tests__/SearchSort.test.js
- src/domain/search/sort/__tests__/__snapshots__/SearchSort.test.js.snap
Previously when you completed a search the screen reader would not give any input. The screen reader would also not give any input on changes to search result order.
Now the screen reader should read the search result count after the user searches for something (as long as it changes).
And the screen reader should also read out the current sort order after it is changed. It'll take some time for the reader to to describe the current state of the dropdown filter so it takes some patience to hear this announcement.
> VAR-292 | Announce changes in search results and search result order

- app/state/selectors/__tests__/authSelectors.test.js
- app/state/selectors/authSelectors.js
The createIsStaffSelector will now build a selector that will return
true when the user has the unit manager role for the resource given as
a parameter.
The manager and admin roles should, at least for now, have the exact
same permission within this UI. As the permission system is not
centralized anywhere else, this selector is the easiest place in the
code to synchronize these permissions.
> VAR-325 | Change createIsStaffSelector to respect manager role

- CHANGELOG.md
- app/pages/reservation/reservation-information/ReservationInformationForm.js
- app/pages/resource/resource-info/ResourceInfo.js
The line breaks in terms should be visible, because they make the
content easier to read.
> VAR-324 | Wrap generic and specific terms 

- app/pages/reservation/reservation-information/Input.js
- app/pages/reservation/reservation-information/ReservationInformationForm.js
- app/pages/reservation/reservation-information/ReservationMetadataField.js
- app/shared/reservation-confirmation/ReservationForm.js
- src/constants/InputPurposes.js
Users should be able to both autocomplete and autofill common form fields. These include for instance `email`, `phone` and `name`. This PR makes the necessary changes which ensure that this feature works on Chrome.
This change is being done, because the lack of autofill support was flagged in an accessibility audit completed for Turku's version of Varaamo. The audit change suggestion referenced [input purposes mentioned in WCAG](https://www.w3.org/TR/WCAG21/#input-purposes). I used a [dev guide](https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill) for Chrome to get extra context. I used [this commit](https://github.com/codepointtku/varaamo/pull/8/commits/bf999fcbf837f4556ab336864e3ae7a64c6b4b9c) from Turku's version as help. Unfortunately I wasn't able to pull …
> VAR-295 | Add autofill support into reservation form

- app/pages/user-reservations/reservation-list/ReservationListItem.js
- app/pages/user-reservations/reservation-list/__tests__/ReservationListItem.test.js
The link in question would appear as "empty" for screen reader users. This change removes the link from tab index, making it inaccessible with `tab` or screen readers, which should resolve the issue.
> VAR-297 | Hide image link from screen reader and keyboard users

- CHANGELOG.md
- app/shared/form-fields/ReservationTimeControls.js
- app/shared/form-fields/__tests__/ReservationTimeControls.test.js
- app/shared/modals/reservation-info/ReservationEditForm.js
- app/shared/modals/reservation-info/ReservationInfoModal.js
- app/shared/modals/reservation-info/__tests__/ReservationEditForm.test.js
- app/shared/modals/reservation-info/__tests__/ReservationInfoModal.test.js
- app/shared/modals/reservation-info/__tests__/reservationInfoModalSelector.test.js
- app/shared/modals/reservation-info/reservationInfoModalSelector.js
- app/state/selectors/__tests__/authSelectors.test.js
- app/state/selectors/authSelectors.js
- docs/PERMISSIONS.md
- src/domain/resource/permissions/__tests__/__snapshots__/utils.test.js.snap
- src/domain/resource/permissions/__tests__/utils.test.js
- src/domain/resource/permissions/constants.js
- src/domain/resource/permissions/utils.js
This PR comes with a story.
When I started working on this PR, the viewer role's permissions were different to that of a manager or admin. I developed the UI in a direction that would allow for us to take singular permissions into account--because the permissions `viewer` had required this.
Previously we were naively using the user's role to allow actions within the UI--after the change we check if the role in question has the specific permissions to do an action. This is a better approach because it's maintainable and extendable, unlike using roles directly. With three roles in play it felt like a valuable change.
Because the API does not return all the permission, some of them are implicit, I replicated the permission matrix from respa into our repo. Unlike with `reservations`, we …
> VAR-276 | Add support for viewer role

- app/pages/user-reservations/UserReservationsPage.js
- app/pages/user-reservations/__tests__/UserReservationsPage.test.js
- app/pages/user-reservations/__tests__/userReservationsPageSelector.test.js
- app/pages/user-reservations/_user-reservations-page.scss
- app/pages/user-reservations/reservation-list/ReservationListContainer.js
- app/pages/user-reservations/reservation-list/ReservationListItem.js
- app/pages/user-reservations/reservation-list/ResourceHydrator.js
- app/pages/user-reservations/reservation-list/__tests__/ReservationListContainer.test.js
- app/pages/user-reservations/reservation-list/__tests__/ReservationListItem.test.js
- app/pages/user-reservations/reservation-list/__tests__/reservationListSelector.test.js
- app/pages/user-reservations/reservation-list/reservationListSelector.js
- app/pages/user-reservations/userReservationsPageSelector.js
- app/shared/reservation-access-code/ReservationAccessCode.js
- app/shared/reservation-access-code/__tests__/ReservationAccessCode.test.js
- app/shared/reservation-access-code/helpers.js
- app/shared/reservation-controls/ReservationControls.js
- app/shared/reservation-controls/ReservationControlsContainer.js
- app/shared/reservation-controls/__tests__/ReservationControls.test.js
- app/shared/reservation-controls/__tests__/ReservationControlsContainer.test.js
- package.json
- src/domain/reservation/manage/pincode/__tests__/ManageReservationsPincode.test.js
- yarn.lock
These changes aim to improve the performance of the my reservations page. The page takes a long time to load as of now and may even crash for devices with lower performance, for instance mobile.
While inspecting the performance issues I, with the help of Samuel, identified two key causes:
1) Requests were configured to fetch a very large set of data (500 pages)
2) Images were loaded in full size
It looked like the reason for the large data set was that the resource object returned inlined to the reservation object is missing some fields which the list requires. To combat this, *all resources*  were fetched into the redux state so that they could be used to "hydrate" the incomplete `reservation.resource` objects. Due to the nature of redux and its normalized state, this must have been seen …
> VAR-331, VAR-332 | Improve performance for my reservations page

- CONTRIBUTING.md
To resolve #1120 we've created a set of guidelines for handling contributions. These are openly accessible at https://github.com/City-of-Helsinki/bestpractice/blob/master/accepting-contributions.md
To make these guidelines accessible through the Varaamo repo, we are adding contributing guidelines that link possible contributors to the resource above.
Closes #1120
> Add preliminary contributing guidelines

- CHANGELOG.md
- app/pages/AppContainer.js
- app/pages/reservation/reservation-information/ReservationInformationForm.js
- app/pages/resource/resource-info/ResourceInfo.js
- app/pages/resource/resource-info/__tests__/ResourceInfo.test.js
- src/common/notificator/create/CreateNotifications.js
- src/common/notificator/create/form/CreateNotificationsForm.js
- src/common/notificator/user/UserNotificator.js
- src/index.js
In these changes I am adding payment terms into the resource information page. They are displayed if the resource has products (`products.length > 0`) and the `paymentTerms` field can be found from the resource object. The payment terms contain information about cancellation policies, so we want to give users easy access to them directly from the resource page.
In these changes I am also replacing hardcoded payment terms within the reservation edit form with the value we receive from the API.
The test version of Respa does not, at the time of writing this PR, yet support the `payment_terms` field, but the task tracking it is in the review phase.
----
**Import firebase as described in console warning**   
Currently firebase gives out warnings for imports that are only compatible with a …
> VAR-330 | Show payment terms defined in resource

- app/pages/user-reservations/reservation-list/ReservationListItem.js
During a refactor, I had made an error when accessing this object. The `completeResource` object is the data field. Asking for `data.data` will yield undefined and results in an error.
Previously, the view would crash when the user had reservations to resources with products.
> VAR-339 | Fix upcoming tab crashing for some users

- CHANGELOG.md
- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- app/shared/modals/reservation-info/ReservationInfoModal.js
- src/constants/ReservationState.js
- src/domain/reservation/manage/action/ManageReservationsDropdown.js
- src/domain/reservation/manage/action/__tests__/ManageReservationsDropdown.test.js
- src/domain/reservation/manage/action/__tests__/__snapshots__/ManageReservationsDropdown.test.js.snap
- src/domain/reservation/modal/ReservationInformationModal.js
- src/domain/reservation/modal/__tests__/ReservationInfomationModal.test.js
- src/domain/reservation/modal/__tests__/__snapshots__/ReservationInfomationModal.test.js.snap
After these changes, approve and deny buttons should be hidden when the `reservation`'s state is not `requested` in these cases:  
1) Dropdown menu in the list of reservations
2) Information modal that the user can access by opening the dropdown and selecting "Information"
The English version of the application should also now use "Approve" instead of "Confirm" when it comes to the forementioned buttons and locations.
> VAR-266 | Usability improvements into reservation management page

- CHANGELOG.md
- app/pages/user-reservations/UserReservationsPage.js
- app/pages/user-reservations/__tests__/UserReservationsPage.test.js
- app/pages/user-reservations/reservation-list/ReservationListContainer.js
- app/pages/user-reservations/reservation-list/ReservationListItem.js
- app/pages/user-reservations/reservation-list/ResourceHydrator.js
- app/pages/user-reservations/reservation-list/__tests__/ReservationListContainer.test.js
- app/pages/user-reservations/reservation-list/__tests__/ReservationListItem.test.js
- app/pages/user-reservations/userReservationsPageSelector.js
- app/shared/_shared.scss
- app/shared/modals/reservation-info/ReservationEditForm.js
- app/shared/modals/reservation-info/ReservationInfoModal.js
- app/shared/modals/reservation-info/ReservationInfoModalContainer.js
- app/shared/modals/reservation-info/__tests__/ReservationInfoModal.test.js
- app/shared/reservation-controls/ReservationControls.js
- app/shared/reservation-controls/ReservationControlsContainer.js
- app/shared/reservation-controls/__tests__/ReservationControls.test.js
- app/shared/reservation-controls/__tests__/ReservationControlsContainer.test.js
- app/shared/reservation-controls/_reservation_controls.scss
- app/state/reducers/ui/reservationsReducer.js
- app/state/selectors/authSelectors.js
- app/utils/__tests__/reservationUtils.test.js
- app/utils/reservationUtils.js
- package.json
- src/domain/resource/permissions/__tests__/utils.test.js
- src/domain/resource/permissions/constants.js
- src/domain/resource/permissions/utils.js
- yarn.lock
This PR contains changes that were needed due to refactors in previous commits. It also contains the changes described in VAR-333, VAR-334 and VAR-335.
Previously the info button was only displayed for a subset of role and permission combinations. Now it should be displayed to everyone.
Previously, when the user clicked on the edit button on `ReservationInfoModal`, an inline form would open within the modal. After these changes, the button will redirect the user into the reservation edit flow instead.
This required no changes--this was already the case before.
I didn't create a subtask for this item, but it was discussed with the PO. A user with no roles, or the role os "reserver", should also be able to access the edit button within the `ReservationInfoModal`.
----
Other changes and …
> VAR-333, VAR-334, VAR-335 | Refactor reservation control buttons in my reservations

- CHANGELOG.md
- src/domain/search/results/SearchListResults.js
- src/domain/search/results/__tests__/SearchListResults.test.js
When counting pages, we want to all pages that have at least some
content. With Math.round, values liek 2.4 would be rounded to 2 and the
0.4 pages worth of resources would be hidden from users.
> VAR-337 | Fix missing results in search results

- CHANGELOG.md
- src/common/calendar/_timePickerCalendar.scss
Previously, when the user hovered on a reservation in the calendar of a
resource that had short business hours, a scroll bar was removed from
the calendar. This caused the width of the calendar to change. This
change would for instance move the remove button for a reservation
enough where a user might have missed their target.
The scroll bar didn't have a purpose to begin with and was caused by
our application styles overflowing a container. As a fix I changed the
rule that caused the unused scroll bar to remove it entirely.
> VAR-341 | Fix scroll bar flickering on short business hours

- CHANGELOG.md
- src/domain/search/__tests__/utils.test.js
- src/domain/search/utils.js
Some premises do not have their names defined in English (or Swedish). In these cases we use the the Finnish name as a fallback.
> VAR-227 | Fix empty values in premise dropdown for English locale

- CHANGELOG.md
- src/common/calendar/_timePickerCalendar.scss
- src/domain/resource/__tests__/utils.test.js
- src/domain/resource/utils.js
Previously the getFullCalendarMaxTime function would return 00:00:00
when a resources closing time was 23:00:00. This caused the max time to
be smaller than the end time, which in turn caused the calendar to not
render any timeslots.
> VAR-340 | Fix calendar failing to render opening time of 23

- CHANGELOG.md
- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- src/common/calendar/TimePickerCalendar.js
- src/common/calendar/_timePickerCalendar.scss
- src/domain/resource/reservationCalendar/ResourceReservationCalendar.js
- src/domain/resource/reservationCalendar/__tests__/__snapshots__/ResourceReservationCalendar.test.js.snap
Calendar is disabled when the current user does not have have permission to make reservations.
> VAR-350 | Disable calendar when no permission to reserve

- CHANGELOG.md
- docs/DEV_DIARY.md
- src/common/calendar/TimePickerCalendar.js
- src/common/calendar/_timePickerCalendar.scss
- src/domain/resource/__tests__/utils.test.js
- src/domain/resource/utils.js
**Trust API when configuring slot size**  
>Some resources have slot sizes that span a greater portion of the day.
For instance, a resource may have a configuration as follows: opening
time of 09:00, closing time of 15:00 and a mininum slot duration of 3
hours. In this case the day has two possible slots: 09:00-11:59 and
12:00-14:59.
>With our previous approach, we did some scaffolding to ensure that the
00:30:00 and 01:00:00 slot sizes worked well even if the API returned
with an unexpected value for slot_size. Because this would have been
laboursome to do for a more open eded set of possible slot sizes, I
removed the special checks. Now the slot size that is returned from the
API gets used as is.
>I also removed the buffer setting and use the slot size as the buffer
instead. This …
> VAR-356 | Allow uneven minute values

- app/pages/reservation/reservation-confirmation/ReservationConfirmation.js
When a reservation is billable and the billing email address is set,
respa will send the reminder email into this address.
> VAR-382 | Show billing address when reservation is billable

- app/shared/modals/reservation-cancel/ReservationCancelModalContainer.js
The resource is not guaranteed to be available when the check is
completed, which causes the check to always return false. This breaks
the logic of the view.
> VAR-383 | Remove initialisation of state

- app/shared/reservation-controls/ReservationControlsContainer.js
- app/shared/reservation-controls/__tests__/ReservationControlsContainer.test.js
- package.json
- yarn.lock
The previous library does not guarantee browser compatibility and our
build setup doesn't transpile the dependency. To avoid bigger changes
in the build process, I just replaced the dependency with a browser
safe alternative.
> VAR-384 | Replace camelcase library

- src/domain/resource/card/ResourceCard.js
- src/domain/resource/card/__tests__/__snapshots__/ResourceCard.test.js.snap
- src/domain/resource/card/_resourceCard.scss
Generally, having two links will make it harder for a screen reader
user to know where they are going. More specifically, the first link
was broken and drew away user attention from the most important click
target that will navigate the user into the resource page.
> VAR-358 | Use a single link in resource card title area

- CHANGELOG.md
- src/domain/resource/__tests__/utils.test.js
- src/domain/resource/constants.js
- src/domain/resource/utils.js
The utility that's used for calculating a reservation price lacked
support for fixed product prices.
> VAR-386 | Fix fixed prices always being zero

- app/pages/resource/ResourcePage.js
- app/pages/resource/__tests__/resourcePageSelector.test.js
- app/pages/resource/_resource-page.scss
- app/pages/resource/resourcePageSelector.js
- app/pages/user-reservations/reservation-list/ReservationListItem.js
- app/pages/user-reservations/reservation-list/_reservation-list.scss
- app/shared/reservation-controls/ReservationControls.js
- app/shared/reservation-controls/_reservation_controls.scss
- src/domain/feature-flags/getIsFeatureEnabled.js
- src/domain/search/filters/filter/_dateFilter.scss
The normal font sizes were corrected previously. They were caused by HDS and were bugs that were "inherited from other" features. These changes look to fix issues with medium and large font sizes. Descriptions can be found from the comments of VAR-360.
**User reservations page, controls button labels overflow containers**
*Fix buttons overflowing on large font sizes*
The buttons were hard coded to a fixed width of 100px which didn't allow them to span even though there was room for it. I changed the layout to a grid layout, which provides more flexibility for the buttons to resizes based on label length. Optimal sizing varies by language and screen size.
I also improved the behaviour of the buttons on small screens.
**Fix access code breaking layout with large font sizes**
The access code …
> VAR-360 | Fix remaining font size issues

- app/assets/styles/customization/espoo/customization.scss
- app/assets/styles/customization/vantaa/customization.scss
Previously Espoo's and Vantaa's versions of Varaamo did not indicate
between types of reservations. In this commit we are removing the
custom styling in order to allow the default colours to come through.
> VAR-394 | Fix lack of color indicator in availability view

- app/assets/styles/_rem-text-size.scss
Due to a copy paste error, the small font size had been set
incorrectly.
> VAR-412 | Fix small font size

- src/domain/reservation/manage/page/__tests__/__snapshots__/ManageReservationsPage.test.js.snap
- src/domain/search/page/__tests__/__snapshots__/SearchPage.test.js.snap
- src/domain/search/utils.js
In the testing environment, the default municipality would be undefined, which ended up in the query, and would break search.
> Fix default municipality breaking search in test environment

- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- src/common/form/fields/TextAreaField.js
- src/domain/reservation/manage/page/ManageReservationsPage.js
- src/domain/reservation/modal/ReservationCancelModal.js
- src/domain/reservation/modal/__tests__/ReservationCancelModal.test.js
- src/domain/reservation/modal/__tests__/__snapshots__/ReservationCancelModal.test.js.snap
- src/domain/reservation/utils.js
- Implement `TextAreaField` component
- Support cancellation raeson for Manage Reservations page
**[VAR-425](https://helsinkisolutionoffice.atlassian.net/browse/VAR-425)**: Manage reservations page: Add support for cancellation reason 
- Log in with an admin account
- With a reservation in place, go to `Manage reservations` page
- Click on `select action` then `cancel` 
- A modal will be open where you can specify the reason and the explanation
> VAR-425 | Manage reservation page: Support for cancellation reason

- src/domain/reservation/manage/action/ManageReservationsDropdown.js
- src/domain/reservation/manage/page/ManageReservationsPage.js
- src/domain/reservation/modal/ReservationInformationModal.js
- src/domain/reservation/modal/__tests__/__snapshots__/ReservationInfomationModal.test.js.snap
- Show Select Action dropdown for canceled reservations, with the ability to display the information modal
- Remove the Cancel Reservation modal from the Reservation Information Modal since the parent component can control it.
Additional unit tests to be added in a follow-up PR
> VAR-442 | Show Select Action dropdown for canceled reservations 

- app/constants/AppConstants.js
- app/i18n/messages/en.json
- app/i18n/messages/fi.json
- app/i18n/messages/sv.json
- package.json
- src/domain/footer/__tests__/__snapshots__/Footer.test.js.snap
- src/domain/reservation/manage/status/ManageReservationsStatus.js
- Avoid null when using constants.
- Add a label that is used when i18n is constructed directly from state name.
- Bump version.
> TILA-2687: fix missing payment states
